export interface Event {
  $key?: string,
  name?: string,
  event_type?: string,
  city?: string,
  district?: string,
  event_category?: string,
  description?: string,
  event_mode?: string,
  date?: Date,
  startDate?: Date,
  endDate?: Date,
  time?: string,
  price?: string,
  lat?: string,
  lng?: string,
}
